services:

  data_processing:  
    build:
      context: .
      dockerfile: ../app/Dockerfile
    ports:
      - 5000:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge